name: Deploy to EC2

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Connect to EC2 and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip << 'EOF'
          cd /path/to/your/app
          git pull origin main
          npm install
          npm run build
          pm2 restart 4
        EOF
