const CUSTOMER_LIST = [
  {
    id: 1,
    customerName: "Esewa Payment",
    health: 10.0,
    arr: "102.23k",
    score: 3,
    lastSeen: "2 days ago",
    lastTouch: "Email 5 days ago",
    stage: "Select Stage",
    // analytics: 3,
    // reporting: 1.0,
  },
  {
    id: 2,
    health: 9.0,
    customerName: "Wall Mart",
    arr: "102.23k",
    score: 5,
    lastSeen: "2 days ago",
    lastTouch: "Email 3 days ago",
    stage: "Adopted",
    // analytics: 3,
    // reporting: 1.0,
  },
  {
    id: 3,
    health: 11.0,
    customerName: "Esewa Payment",
    arr: "102.23k",
    score: 4,
    lastSeen: "1 days ago",
    lastTouch: "Email 2 days ago",
    stage: "Onboarding",
    // analytics: 2,
    // reporting: 2.0,
  },
  {
    id: 4,
    health: 11.0,
    customerName: "Esewa Payment",
    arr: "102.23k",
    score: 4,
    lastSeen: "1 days ago",
    lastTouch: "Email 2 days ago",
    stage: "Renewed",
    // analytics: 2,
    // reporting: 2.0,
  },
  {
    id: 5,
    health: 11.0,
    customerName: "Esewa Payment",
    arr: "102.23k",
    score: 4,
    lastSeen: "1 days ago",
    lastTouch: "Email 2 days ago",
    stage: "Adopted",
    // analytics: 2,
    // reporting: 2.0,
  },
  {
    id: 6,
    health: 11.0,
    customerName: "NCC",
    arr: "102.23k",
    score: 4,
    lastSeen: "1 days ago",
    lastTouch: "Email 2 days ago",
    stage: "Onboarding",
    // analytics: 2,
    // reporting: 2.0,
  },
  {
    id: 7,
    health: 11.0,
    customerName: "Anglo Gold",
    arr: "102.23k",
    score: 4,
    lastSeen: "1 days ago",
    lastTouch: "Email 2 days ago",
    stage: "Onboarding",
    // analytics: 2,
    // reporting: 2.0,
  },
  {
    id: 8,
    health: 11.0,
    customerName: "Congent Health",
    arr: "102.23k",
    score: 4,
    lastSeen: "1 days ago",
    lastTouch: "Email 2 days ago",
    stage: "Adopted",
    // analytics: 2,
    // reporting: 2.0,
  },
  {
    id: 9,
    health: 11.0,
    customerName: "Phone Pay",
    arr: "102.23k",
    score: 4,
    lastSeen: "1 days ago",
    lastTouch: "Email 2 days ago",
    stage: "Onboarding",
    // analytics: 2,
    // reporting: 2.0,
  },
]

const CUSTOMER_LIST_STAGES = [
  "Trial",
  "Subscribed",
  "Onboarding",
  "Activated",
  "Renewed",
  "Matured",
  "Churned",
]
// Trial, Subscribed, Onboarding, Activated,  Renewal, Matured, Churned

export { CUSTOMER_LIST, CUSTOMER_LIST_STAGES }
