version: "3.8"

services:
  nextjs:
    image: sabin21/ai-assistant-frontend:v1
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: always
