const MOCK_DATA = {
  customerId: "789012",
  name: "Sarah Smith",
  company: "Acme Corp.",
  recentTransactions: [
    {
      transactionId: "trans001",
      date: "2024-08-25T14:30:00.000Z",
      amount: 2500.0,
      currency: "USD",
      description: "Quarterly Subscription Payment",
      status: "Completed",
    },
    {
      transactionId: "trans002",
      date: "2024-08-30T10:15:00.000Z",
      amount: 300.0,
      currency: "USD",
      description: "Add-on Service Purchase",
      status: "Completed",
    },
  ],
  activityLogs: [
    {
      logId: "log001",
      date: "2024-08-26T09:00:00.000Z",
      type: "email",
      details: "Sent renewal reminder email to Sarah Smith",
      status: "Sent",
    },
    {
      logId: "log002",
      date: "2024-08-29T11:00:00.000Z",
      type: "call",
      details: "Phone call with Sarah Smith regarding upcoming product updates",
      status: "Completed",
    },
    {
      logId: "log003",
      date: "2024-08-31T08:45:00.000Z",
      type: "support_ticket",
      details: "Opened support ticket for issue with invoice",
      status: "Resolved",
    },
  ],
}

const LOGIN_DETAIL_MOCK_DATA = [
  {
    hotel: "Hilton",
    system: "PMS",
    email: "bob.lee@hiltonbook.com",
    date: "2024-09-10",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "bob.lee@hiltonbook.com",
    date: "2024-09-08",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "alice.johnson@hiltonbook.com",
    date: "2024-08-12",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "jane.smith@hiltonbook.com",
    date: "2024-08-27",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "chris.evans@hiltonbook.com",
    date: "2024-09-18",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "john.doe@hiltonbook.com",
    date: "2024-09-04",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "alice.johnson@hiltonbook.com",
    date: "2024-09-07",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "bob.lee@hiltonbook.com",
    date: "2024-09-04",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "bob.lee@hiltonbook.com",
    date: "2024-09-19",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "bob.lee@hiltonbook.com",
    date: "2024-09-03",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "alice.johnson@hiltonbook.com",
    date: "2024-09-10",
    time: "14:03:38",
    action: "Login",
  },
  {
    hotel: "Hilton",
    system: "PMS",
    email: "chris.evans@hiltonbook.com",
    date: "2024-08-28",
    time: "14:03:38",
    action: "Login",
  },
  // Continue for other records...
  {
    hotel: "HolidayInn",
    system: "PMS",
    email: "steve.adams@holidayinnbook.com",
    date: "2024-08-29",
    time: "14:16:55",
    action: "Login",
  },
  {
    hotel: "HolidayInn",
    system: "PMS",
    email: "emma.davis@holidayinnbook.com",
    date: "2024-08-15",
    time: "14:16:55",
    action: "Login",
  },
  {
    hotel: "HolidayInn",
    system: "PMS",
    email: "sophia.clark@holidayinnbook.com",
    date: "2024-08-18",
    time: "14:16:55",
    action: "Login",
  },
  {
    hotel: "HolidayInn",
    system: "PMS",
    email: "anna.brown@holidayinnbook.com",
    date: "2024-08-31",
    time: "14:16:55",
    action: "Login",
  },
  {
    hotel: "HolidayInn",
    system: "PMS",
    email: "steve.adams@holidayinnbook.com",
    date: "2024-06-30",
    time: "14:16:55",
    action: "Login",
  },
  // Continue for other HolidayInn records...
]

export { MOCK_DATA, LOGIN_DETAIL_MOCK_DATA }
