import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import { ToastContainer } from "react-toastify"
import Hydration from "./Hydration"
const poppins = Poppins({ subsets: ["latin"], weight: "400" })
import Script from "next/script" // ✅ import Script

export const metadata: Metadata = {
  title: "CoWrkr- Customer Success CoWorker",
  description: "Generated by create next app",
  other: {
    "X-Frame-Options": "DENY",
    "X-Content-Type-Options": "nosniff",
    "X-XSS-Protection": "1; mode=block",
    "Referrer-Policy": "strict-origin-when-cross-origin",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="X-Frame-Options" content="DENY" />
        <meta httpEquiv="X-Content-Type-Options" content="nosniff" />
        <meta httpEquiv="X-XSS-Protection" content="1; mode=block" />
        <meta
          httpEquiv="Referrer-Policy"
          content="strict-origin-when-cross-origin"
        />
        <meta
          httpEquiv="Permissions-Policy"
          content="camera=(), microphone=(), geolocation=()"
        />
      </head>
      <body className={poppins.className}>
        <ToastContainer />
        {/* ✅ Load tracker script after page becomes interactive */}
        <Script src="/tracker.js" strategy="afterInteractive" />
        {children}
      </body>
    </html>
  )
}
