import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import { ToastContainer } from "react-toastify"
import Hydration from "./Hydration"
const poppins = Poppins({ subsets: ["latin"], weight: "400" })
import Script from "next/script" // ✅ import Script

export const metadata: Metadata = {
  title: "CoWrkr- Customer Success CoWorker",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ToastContainer />
        {/* ✅ Load tracker script after page becomes interactive */}
        <Script src="/tracker.js" strategy="afterInteractive" />
        {children}
      </body>
    </html>
  )
}
