const CUSTOMER_SURVEY = [
  {
    id: 1,
    date: "2024/04/22",
    user: "Jhon doe",
    rating: 10,
    feedback:
      "Great service! The agent was quick and resolved my issue efficiently.",
  },
  {
    id: 2,
    date: "2024/04/12",
    user: "Jhon felix",
    rating: 3,
    feedback:
      "Low satisfactory service! The agent was quick and resolved my issue efficiently.",
  },
  {
    id: 3,
    date: "2024/05/21",
    user: "Jhon felix",
    rating: 6,
    feedback:
      "Medium service! The agent was quick and resolved my issue efficiently.",
  },
  {
    id: 4,
    date: "2024/06/22",
    user: "Stuart reamer",
    rating: 10,
    feedback:
      "Great service! The agent was quick and resolved my issue efficiently.",
  },
  {
    id: 5,
    date: "2024/11/22",
    user: "Jhon felix",
    rating: 6,
    feedback: "Very helpful and friendly. Solved my problem within minutes.",
  },
  {
    id: 6,
    date: "2024/11/22",
    user: "Alison root",
    rating: 3,
    feedback: "Very helpful and friendly. Solved my problem within minutes.",
  },
  {
    id: 7,
    date: "2024/11/24",
    user: "Alison root",
    rating: 10,
    feedback: "Very helpful and friendly. Solved my problem within minutes.",
  },
  {
    id: 8,
    date: "2024/12/22",
    user: "Alison root",
    rating: 3,
    feedback: "Very helpful and friendly. Solved my problem within minutes.",
  },
  {
    id: 9,
    date: "2024/11/11",
    user: "Andrew cape",
    rating: 6,
    feedback: "Very helpful and friendly. Solved my problem within minutes.",
  },
  {
    id: 10,
    date: "2024/11/15",
    user: "Stuart reamer",
    rating: 3,
    feedback: "Very helpful and friendly. Solved my problem within minutes.",
  },
]

const UPSELL_OPPORTUNITIES = [
  {
    id: 1,
    opportunity: "AI-Powered Automation Enhancement",
    product: "Face recognition checking",
    feature: "Email",
    stage: "Appt Scheduled",
    recorded_date: "2024/04/21",
    closed_date: "2024/04/31",
    owner: "jim@test.com",
    notes:
      "Leverage AI efficiency and accuracy to automate and optimize repetitive processes, improving efficiency.",
  },
  {
    id: 2,
    opportunity: "Predictive Model Tuning",
    product: "Behr Premium Plus Ultra 1-Gallon Interior Paint",
    feature: "Auto notify",
    stage: "Qualifying",
    recorded_date: "2024/04/21",
    closed_date: "2024/05/21",
    owner: "jim@test.com",
    notes:
      "Leverage AI to automate and optimize repetitive processes, improving efficiency and accuracy.",
  },
  {
    id: 3,
    opportunity: "Machine Learning Algorithm Optimization",
    product: "AI Chat bot for guest support",
    feature: "Email",
    stage: "Appt Scheduled",
    recorded_date: "2024/04/21",
    closed_date: "2024/06/21",
    owner: "sarah@test.com",
    notes:
      "Leverage AI to automate and optimize repetitive processes, improving efficiency.",
  },
  {
    id: 4,
    opportunity: "Natural Language Processing Module",
    product: "Ryobi 18V ONE+ Cordless Drill/Driver Kit",
    feature: "Phone",
    stage: "Appt Scheduled",
    recorded_date: "2024/04/21",
    closed_date: "2024/04/22",
    owner: "sarah@test.com",
    notes:
      "Leverage AI to automate and optimize repetitive processes, improving efficiency and accuracy.",
  },
  {
    id: 5,
    opportunity: "Data Preprocessing Pipeline",
    product: "Ryobi 18V ONE+ Cordless Drill/Driver Kit",
    feature: "Phone",
    stage: "Contract Sent",
    recorded_date: "2024/04/21",
    closed_date: "2024/04/23",
    owner: "bhattachas@hotmail.com",
    notes:
      "Leverage AI to automate and optimize repetitive processes, improving efficiency.",
  },
  {
    id: 6,
    opportunity: "AI Model Deployment on Cloud",
    product: "Ryobi 18V ONE+ Cordless Drill/Driver Kit",
    feature: "Phone",
    stage: "Appt Scheduled",
    recorded_date: "2024/04/21",
    closed_date: "2024/07/21",
    owner: "bhattachas@hotmail.com",
    notes:
      "Leverage AI to automate and optimize repetitive processes, improving accuracy.",
  },
  {
    id: 7,
    opportunity: "Training Data Augmentation",
    product: "Ryobi 18V ONE+ Cordless Drill/Driver Kit",
    feature: "Auto notify",
    stage: "Contract Sent",
    recorded_date: "2024/04/21",
    closed_date: "2024/08/21",
    owner: "jim@test.com",
    notes:
      "Leverage AI to automate and improving efficiency by optimizing repetitive processes.",
  },
  {
    id: 8,
    opportunity: "AI Model Performance Benchmarking",
    product: "Behr Premium Plus Ultra 1-Gallon Interior Paint",
    feature: "Auto notify",
    stage: "Qualifying",
    recorded_date: "2024/04/21",
    closed_date: "2024/10/21",
    owner: "jim@test.com",
    notes:
      "Leverage AI to automate and optimize repetitive processes, improving efficiency.",
  },
  {
    id: 9,
    opportunity: "Reinforcement Learning Simulation",
    product: "Behr Premium Plus Ultra 1-Gallon Interior Paint",
    feature: "Email",
    stage: "Appt Scheduled",
    recorded_date: "2024/04/21",
    closed_date: "2024/04/21",
    owner: "jim@test.com",
    notes:
      "Leverage AI to automate and optimize repetitive processes, improving efficiency.",
  },
  {
    id: 10,
    opportunity: "AI Ethics & Bias Testing",
    product: "Behr Premium Plus Ultra 1-Gallon Interior Paint",
    feature: "Email",
    stage: "Qualifying",
    recorded_date: "2024/04/21",
    closed_date: "2024/04/21",
    owner: "jim@test.com",
    notes:
      "Leverage AI to automate and optimize repetitive processes, improving accuracy and reducing bias.",
  },
]

const SUPPORT_TICKETS = [
  {
    ticket_no: 1,
    title: "AI-Powered Automation Enhancement",
    reported_by: "Jhon doe",
    reported_date: "2024/01/12",
    last_updated: "2 days ago",
    updated_by: "Jhon doe",
    status: "Pending",
  },
  {
    ticket_no: 2,
    title: "Predictive Model Tuning",
    reported_by: "Jhon felix",
    reported_date: "2024/01/12",
    last_updated: "2 days ago",
    updated_by: "Jhon felix",
    status: "Resolved",
  },
  {
    ticket_no: 3,
    title: "Machine Learning Algorithm Optimization",
    reported_by: "Jhon felix",
    reported_date: "2024/01/12",
    last_updated: "2 days ago",
    updated_by: "Jhon felix",
    status: "Pending",
  },
  {
    ticket_no: 4,
    title: "Natural Language Processing Module",
    reported_by: "Stuart reamer",
    reported_date: "2024/01/12",
    last_updated: "2 days ago",
    updated_by: "Jhon felix",
    status: "In progress",
  },
  {
    ticket_no: 5,
    title: "Data Preprocessing Pipeline",
    reported_by: "Jhon felix",
    reported_date: "2024/01/12",
    last_updated: "2 days ago",
    updated_by: "Jhon felix",
    status: "In progress",
  },
  {
    ticket_no: 6,
    title: "AI Model Deployment on Cloud",
    reported_by: "Alison root",
    reported_date: "2024/01/12",
    last_updated: "2 days ago",
    updated_by: "Jhon felix",
    status: "Not assigned",
  },
  {
    ticket_no: 7,
    title: "Training Data Augmentation",
    reported_by: "Alison root",
    reported_date: "2024/01/12",
    last_updated: "2 days ago",
    updated_by: "Stuart reamer",
    status: "Resolved",
  },
  {
    ticket_no: 8,
    title: "AI Model Performance Benchmarking",
    reported_by: "Alison root",
    reported_date: "2024/01/12",
    last_updated: "2 days ago",
    updated_by: "Jhon felix",
    status: "Resolved",
  },
  {
    ticket_no: 9,
    title: "AI Ethics & Bias Testing",
    reported_by: "Andrew cape",
    reported_date: "2024/01/12",
    last_updated: "2 days ago",
    updated_by: "Alison root",
    status: "In progress",
  },
  {
    ticket_no: 10,
    title: "Reinforcement Learning Simulation",
    reported_by: "Stuart reamer",
    reported_date: "2024/01/12",
    last_updated: "2 days ago",
    updated_by: "Jhon felix",
    status: "Not assigned",
  },
]

export { CUSTOMER_SURVEY, UPSELL_OPPORTUNITIES, SUPPORT_TICKETS }
