const initialEmails = [
  {
    _id: 1,
    from: "john.doe@example.com",
    to: "team@project.com",
    subject: "Weekly Project Update",
    datetime: new Date("2024-03-20T09:00:00"),
    status: "open",
  },
  {
    _id: 2,
    from: "hr@company.com",
    to: "employee@example.com",
    subject: "Mandatory Training Reminder",
    datetime: new Date("2024-03-19T11:00:00"),
    status: "open",
  },
  {
    _id: 3,
    from: "alice.smith@partners.com",
    to: "legal@company.com",
    subject: "Contract Review Request",
    datetime: new Date("2024-03-18T14:45:00"),
    status: "done",
  },
  {
    _id: 4,
    from: "support@service.com",
    to: "user123@example.com",
    subject: "Password Reset Instructions",
    datetime: new Date("2024-03-18T16:30:00"),
    status: "open",
  },
  {
    _id: 5,
    from: "newsletter@shop.com",
    to: "subscriber@example.com",
    subject: "Exclusive Spring Sale!",
    datetime: new Date("2024-03-17T08:15:00"),
    status: "done",
  },
  {
    _id: 6,
    from: "james.brown@consulting.com",
    to: "ceo@company.com",
    subject: "Quarterly Strategy Meeting",
    datetime: new Date("2024-03-21T10:00:00"),
    status: "open",
  },
  {
    _id: 7,
    from: "team@event.com",
    to: "guest@example.com",
    subject: "Invitation: Annual Tech Conference",
    datetime: new Date("2024-03-16T13:00:00"),
    status: "done",
  },
  {
    _id: 8,
    from: "recruitment@company.com",
    to: "candidate@example.com",
    subject: "Interview Schedule Confirmation",
    datetime: new Date("2024-03-22T09:30:00"),
    status: "open",
  },
  {
    _id: 9,
    from: "alerts@bank.com",
    to: "user456@example.com",
    subject: "Unusual Login Attempt Detected",
    datetime: new Date("2024-03-15T20:45:00"),
    status: "done",
  },
  {
    _id: 10,
    from: "marketing@ecommerce.com",
    to: "customer@example.com",
    subject: "Your Wishlist is on Sale!",
    datetime: new Date("2024-03-19T18:00:00"),
    status: "done",
  },
  {
    _id: 11,
    from: "alerts@bank.com",
    to: "user456@example.com",
    subject: "Unusual Login Attempt Detected",
    datetime: new Date("2024-03-15T20:45:00"),
    status: "done",
  },
  {
    _id: 12,
    from: "marketing@ecommerce.com",
    to: "customer@example.com",
    subject: "Your Wishlist is on Sale!",
    datetime: new Date("2024-03-19T18:00:00"),
    status: "done",
  },
  {
    _id: 13,
    from: "alerts@bank.com",
    to: "user456@example.com",
    subject: "Unusual Login Attempt Detected",
    datetime: new Date("2024-03-15T20:45:00"),
    status: "done",
  },
  {
    _id: 14,
    from: "marketing@ecommerce.com",
    to: "customer@example.com",
    subject: "Your Wishlist is on Sale!",
    datetime: new Date("2024-03-19T18:00:00"),
    status: "done",
  },
  {
    _id: 15,
    from: "alerts@bank.com",
    to: "user456@example.com",
    subject: "Unusual Login Attempt Detected",
    datetime: new Date("2024-03-15T20:45:00"),
    status: "done",
  },
  {
    _id: 16,
    from: "marketing@ecommerce.com",
    to: "customer@example.com",
    subject: "Your Wishlist is on Sale!",
    datetime: new Date("2024-03-19T18:00:00"),
    status: "done",
  },
  {
    _id: 17,
    from: "info@healthcare.com",
    to: "patient@example.com",
    subject: "Appointment Confirmation",
    datetime: new Date("2024-03-20T12:00:00"),
    status: "open",
  },
  {
    _id: 18,
    from: "team@education.com",
    to: "student@example.com",
    subject: "Course Enrollment Successful",
    datetime: new Date("2024-03-21T10:00:00"),
    status: "done",
  },
]

export default initialEmails
