const initialEmails = [
  {
    _id: 1,
    event: "new_lead",
    action: "outreach",
    to: "team@project.com",
    subject: "Weekly Project Update",
    datetime: new Date("2024-03-20T09:00:00"),
    status: "open",
  },
  {
    _id: 2,
    event: "follow_up",
    action: "email",
    to: "client@example.com",
    subject: "Follow-Up on Proposal",
    datetime: new Date("2024-03-21T10:00:00"),
    status: "open",
  },
  {
    _id: 3,
    event: "feedback_request",
    action: "survey",
    to: "feedback@company.com",
    subject: "Customer Feedback Request",
    datetime: new Date("2024-03-22T11:30:00"),
    status: "done",
  },
  {
    _id: 4,
    event: "escalation",
    action: "call",
    to: "support@service.com",
    subject: "Urgent Issue Escalation",
    datetime: new Date("2024-03-23T14:00:00"),
    status: "open",
  },
  {
    _id: 5,
    event: "appointment_reminder",
    action: "reminder",
    to: "appointments@healthcare.com",
    subject: "Your Appointment Reminder",
    datetime: new Date("2024-03-24T09:15:00"),
    status: "open",
  },
  {
    _id: 6,
    event: "new_lead",
    action: "outreach",
    to: "sales@company.com",
    subject: "New Lead Contacted",
    datetime: new Date("2024-03-25T10:00:00"),
    status: "done",
  },
  {
    _id: 7,
    event: "newsletter",
    action: "send_email",
    to: "subscribers@newsletter.com",
    subject: "Monthly Updates",
    datetime: new Date("2024-03-26T08:00:00"),
    status: "done",
  },
  {
    _id: 8,
    event: "promotion",
    action: "email_campaign",
    to: "promo@retail.com",
    subject: "Spring Sale Promotion",
    datetime: new Date("2024-03-27T09:00:00"),
    status: "done",
  },
  {
    _id: 9,
    event: "customer_support",
    action: "follow_up",
    to: "helpdesk@support.com",
    subject: "Follow-Up on Ticket #12345",
    datetime: new Date("2024-03-28T15:00:00"),
    status: "open",
  },
  {
    _id: 10,
    event: "survey_reminder",
    action: "reminder",
    to: "feedback@survey.com",
    subject: "Complete Your Survey",
    datetime: new Date("2024-03-29T11:00:00"),
    status: "open",
  },
  {
    _id: 11,
    event: "billing_issue",
    action: "notify",
    to: "billing@finance.com",
    subject: "Invoice #98765 Issue",
    datetime: new Date("2024-03-30T13:30:00"),
    status: "done",
  },
  {
    _id: 12,
    event: "product_launch",
    action: "announcement",
    to: "marketing@launch.com",
    subject: "New Product Launch Details",
    datetime: new Date("2024-04-01T10:00:00"),
    status: "done",
  },
  {
    _id: 13,
    event: "new_lead",
    action: "introduction",
    to: "sales@enterprise.com",
    subject: "Introducing Your Sales Representative",
    datetime: new Date("2024-04-02T14:00:00"),
    status: "open",
  },
  {
    _id: 14,
    event: "training_session",
    action: "invitation",
    to: "hr@training.com",
    subject: "Invitation to Training Session",
    datetime: new Date("2024-04-03T16:00:00"),
    status: "done",
  },
  {
    _id: 15,
    event: "customer_review",
    action: "request_review",
    to: "customers@reviews.com",
    subject: "We Value Your Feedback!",
    datetime: new Date("2024-04-04T12:00:00"),
    status: "done",
  },
  {
    _id: 16,
    event: "new_lead",
    action: "follow_up",
    to: "lead@marketing.com",
    subject: "Follow-Up on Your Interest",
    datetime: new Date("2024-04-05T09:30:00"),
    status: "open",
  },
  {
    _id: 17,
    event: "webinar_invitation",
    action: "invite",
    to: "attendees@webinar.com",
    subject: "Join Our Upcoming Webinar",
    datetime: new Date("2024-04-06T17:00:00"),
    status: "done",
  },
  {
    _id: 18,
    event: "payment_reminder",
    action: "notify",
    to: "finance@payment.com",
    subject: "Payment Due Reminder",
    datetime: new Date("2024-04-07T10:00:00"),
    status: "open",
  },
  {
    _id: 19,
    event: "customer_retention",
    action: "survey",
    to: "support@retention.com",
    subject: "Help Us Improve!",
    datetime: new Date("2024-04-08T13:00:00"),
    status: "open",
  },
  {
    _id: 20,
    event: "promotion",
    action: "discount_offer",
    to: "offers@promo.com",
    subject: "Exclusive Discount Just for You",
    datetime: new Date("2024-04-09T14:00:00"),
    status: "done",
  },
]

export default initialEmails
